### ISSUE TITLE
Gap in labels

### ISSUE THREAD

**Issue by binodthapachhetry** [adityaponnada/signaligner_annotations_analysis#2]
I looked at the two label files you sent me. There seem to be gaps in time that do not have any associated labels. I know this is expected. However, this creates extra challenge writing script that automatically maps the raw data, within a 30-second window, to a label.

**Comment by adityaponnada** [comment]
@binodthapachhetry the gaps were in SWaN output as well because the dataset contained 0,0,0 values in between. In this case, what do you think the recommended way of labeling them would be? Because I think SWaN would ignore it anyway right? Should we label it as "unknown"?
